# -*- coding: utf-8 -*-
"""Ecommerce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1txut2XF20Ve9N7ijw6zEOtnsrz-gu8m-
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import TruncatedSVD

# Load dataset
file_path = "/content/Makeup_Products_Dataset.csv"
df = pd.read_csv(file_path)

# Select relevant numerical features
numeric_features = df[['price', 'customer_rating', 'repurchase_intent']]

# Convert to NumPy matrix
numeric_matrix = numeric_features.to_numpy()

# --- Matrix Multiplication ---
# Compute the dot product of the feature matrix
result_matrix = np.dot(numeric_matrix.T, numeric_matrix)

# Convert result to DataFrame
result_df = pd.DataFrame(result_matrix,
                         index=['price', 'customer_rating', 'repurchase_intent'],
                         columns=['price', 'customer_rating', 'repurchase_intent'])

# --- Heatmap Visualization ---
plt.figure(figsize=(8, 6))
sns.heatmap(result_df, annot=True, fmt=".2f", cmap="coolwarm", linewidths=0.5)
plt.title("Matrix Multiplication Result Heatmap")
plt.xlabel("Features")
plt.ylabel("Features")
plt.show()

# --- Matrix Factorization using SVD ---
svd = TruncatedSVD(n_components=2)  # Reducing to 2 latent factors
factorized_matrix = svd.fit_transform(numeric_matrix)

# Convert results to DataFrame
factorized_df = pd.DataFrame(factorized_matrix, columns=['Factor 1', 'Factor 2'])

# --- Scatter Plot Visualization ---
plt.figure(figsize=(8, 6))
plt.scatter(factorized_df['Factor 1'], factorized_df['Factor 2'], alpha=0.5)
plt.xlabel("Latent Factor 1")
plt.ylabel("Latent Factor 2")
plt.title("Matrix Factorization Visualization using SVD")
plt.grid(True)
plt.show()